language: php

dist: trusty

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=4
#    - php: 7.0
#      env: DB=MYSQL
#   - php: 7.1
#      env: DB=MYSQL

before_script:
- phpenv rehash
- composer self-update
- git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
- php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
- cd ~/builds/ss
- ls

#before_script:
  # Init PHP
#  - phpenv rehash
#  - phpenv config-rm xdebug.ini
#  - echo 'memory_limit = 2048M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini


#before_script:
  # Init PHP
#  - phpenv rehash
#  - phpenv config-rm xdebug.ini
#  - composer validate
#  - composer require silverstripe/recipe-cms 1.0.x-dev  --no-update
#  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile


script:
- vendor/bin/phpunit silverstripe-acecodeeditor/tests/