
language: php


dist: trusty


matrix:
  include:
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=4
    - php: 7.0
      env: DB=MYSQL CORE_RELEASE=4
    - php: 7.1
      env: DB=MYSQL CORE_RELEASE=4


before_script:
- phpenv rehash
- composer self-update
- git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
- php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
- cd ~/builds/ss


script:
- vendor/bin/phpunit silverstripe-acecodeeditor/tests/
